// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: search_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ingestion payload containing the raw web page data stream
type ProcessDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl      string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	RawHtmlContent string                 `protobuf:"bytes,2,opt,name=raw_html_content,json=rawHtmlContent,proto3" json:"raw_html_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_search_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_search_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDocumentRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ProcessDocumentRequest) GetRawHtmlContent() string {
	if x != nil {
		return x.RawHtmlContent
	}
	return ""
}

// Computed index metadata return block
type ProcessDocumentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorLog         string                 `protobuf:"bytes,2,opt,name=error_log,json=errorLog,proto3" json:"error_log,omitempty"`
	PageTitle        string                 `protobuf:"bytes,3,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	MetaDescription  string                 `protobuf:"bytes,4,opt,name=meta_description,json=metaDescription,proto3" json:"meta_description,omitempty"`
	TokenFrequencies map[string]int32       `protobuf:"bytes,5,rep,name=token_frequencies,json=tokenFrequencies,proto3" json:"token_frequencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Term frequencies calculated by C++
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_search_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_search_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessDocumentResponse) GetErrorLog() string {
	if x != nil {
		return x.ErrorLog
	}
	return ""
}

func (x *ProcessDocumentResponse) GetPageTitle() string {
	if x != nil {
		return x.PageTitle
	}
	return ""
}

func (x *ProcessDocumentResponse) GetMetaDescription() string {
	if x != nil {
		return x.MetaDescription
	}
	return ""
}

func (x *ProcessDocumentResponse) GetTokenFrequencies() map[string]int32 {
	if x != nil {
		return x.TokenFrequencies
	}
	return nil
}

var File_search_engine_proto protoreflect.FileDescriptor

const file_search_engine_proto_rawDesc = "" +
	"\n" +
	"\x13search_engine.proto\x12\rsearch_engine\"a\n" +
	"\x16ProcessDocumentRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12(\n" +
	"\x10raw_html_content\x18\x02 \x01(\tR\x0erawHtmlContent\"\xca\x02\n" +
	"\x17ProcessDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_log\x18\x02 \x01(\tR\berrorLog\x12\x1d\n" +
	"\n" +
	"page_title\x18\x03 \x01(\tR\tpageTitle\x12)\n" +
	"\x10meta_description\x18\x04 \x01(\tR\x0fmetaDescription\x12i\n" +
	"\x11token_frequencies\x18\x05 \x03(\v2<.search_engine.ProcessDocumentResponse.TokenFrequenciesEntryR\x10tokenFrequencies\x1aC\n" +
	"\x15TokenFrequenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012t\n" +
	"\rHTMLProcessor\x12c\n" +
	"\x12ExtractAndTokenize\x12%.search_engine.ProcessDocumentRequest\x1a&.search_engine.ProcessDocumentResponseB-Z+services/crawler-gateway-go/internal/ipc/pbb\x06proto3"

var (
	file_search_engine_proto_rawDescOnce sync.Once
	file_search_engine_proto_rawDescData []byte
)

func file_search_engine_proto_rawDescGZIP() []byte {
	file_search_engine_proto_rawDescOnce.Do(func() {
		file_search_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_engine_proto_rawDesc), len(file_search_engine_proto_rawDesc)))
	})
	return file_search_engine_proto_rawDescData
}

var file_search_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_engine_proto_goTypes = []any{
	(*ProcessDocumentRequest)(nil),  // 0: search_engine.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 1: search_engine.ProcessDocumentResponse
	nil,                             // 2: search_engine.ProcessDocumentResponse.TokenFrequenciesEntry
}
var file_search_engine_proto_depIdxs = []int32{
	2, // 0: search_engine.ProcessDocumentResponse.token_frequencies:type_name -> search_engine.ProcessDocumentResponse.TokenFrequenciesEntry
	0, // 1: search_engine.HTMLProcessor.ExtractAndTokenize:input_type -> search_engine.ProcessDocumentRequest
	1, // 2: search_engine.HTMLProcessor.ExtractAndTokenize:output_type -> search_engine.ProcessDocumentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_engine_proto_init() }
func file_search_engine_proto_init() {
	if File_search_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_engine_proto_rawDesc), len(file_search_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_engine_proto_goTypes,
		DependencyIndexes: file_search_engine_proto_depIdxs,
		MessageInfos:      file_search_engine_proto_msgTypes,
	}.Build()
	File_search_engine_proto = out.File
	file_search_engine_proto_goTypes = nil
	file_search_engine_proto_depIdxs = nil
}
